version: 2.1
jobs:
  build:
    docker:
      - image: cyrusbehr/sdk_design

    steps:
      - restore_cache:
          keys:
            - source-v1-{{ .Branch }}-

      - checkout

      - save_cache:
          key: source-v1-{{ .Branch }}-
          paths:
            - ".git"

      - restore_cache:
          key: 3rdparty_ncnn-{{ .Environment.CIRCLE_JOB }}-{{ checksum "./3rdparty/build_ncnn.sh" }}
      - restore_cache:
          key: 3rdparty_opencv-{{ .Environment.CIRCLE_JOB }}-{{ checksum "./3rdparty/build_opencv.sh" }}

      - run:
          name: Build 3rd party libraries
          command: |
            cd ~/project/3rdparty
