version: 2.1
jobs:
  build:
    docker:
      - image: cyrusbehr/sdk_design

    steps:
      - checkout

      - restore_cache:
          key: 3rdparty_ncnn-{{ .Environment.CIRCLE_JOB }}-{{ checksum "./3rdparty/build_ncnn.sh" }}
      - restore_cache:
          key: 3rdparty_opencv-{{ .Environment.CIRCLE_JOB }}-{{ checksum "./3rdparty/build_opencv.sh" }}

      - run:
          name: Build 3rd party libraries
          command: |
            cd ~/project/3rdparty
            ./build_pybind11.sh
            ./build_catch.sh
            test -e ncnn-20200916 || ./build_ncnn.sh
            test -e opencv-4.4.0 || ./build_opencv.sh


      - save_cache:
          key: 3rdparty_ncnn-{{ .Environment.CIRCLE_JOB }}-{{ checksum "./3rdparty/build_ncnn.sh" }}
          paths:
            - ./3rdparty/ncnn-20200916

      - save_cache:
          key: 3rdparty_opencv-{{ .Environment.CIRCLE_JOB }}-{{ checksum "./3rdparty/build_opencv.sh" }}
          paths:
            - ./3rdparty/opencv-4.4.0

      - run:
          name: Build for amd64
          command: |
            cd ~/project
            mkdir build_amd64
            cd build_amd64
            cmake ..
            make -j4

      - run:
          name: Run unit tests
          command: |
            cd ~/project/build_amd64
            ./test

      - run:
          name: Build for arm32
          command: |
            cd ~/project
            mkdir build_arm32
            cd build_arm32
            cmake -DBUILD_ARM32=ON ..
            make -j4

      - run:
          name: Build for arm64
          command: |
            cd ~/project
            mkdir build_arm64
            cd build_arm64
            cmake -DBUILD_ARM64=ON ..
            make -j4