FROM ubuntu:18.04

RUN apt-get update && apt-get install -y build-essential g++-aarch64-linux-gnu gcc-arm-linux-gnueabihf binutils-arm-linux-gnueabihf g++-arm-linux-gnueabihf \
python3.8 python3-pip doxygen wget zip && pip3 install cmake